before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: phY2pYAMlUoe0DoEZDd/kwruqfl4MeB+RSEw7W1QVi0yGVIGfsA5ke7OiqbtGAgnL2ulSmq+PbuKbz6brNa6iaeAc+pU8eUo4BJo8myGQQdwxDhZjDPHLZIadtrZfO2Alykk4pHGkdqpa9H+FIIZbQSgTi0V9IbZSyERdd6mmnXLXS7ZaXC4yf8ecQ8M9iX9n0pVTYmdl8RJC0CMJAetlO6fCeErlX/eEg0nVupUpqIdrBui3XNipIElaiIDDe9bKD3Crw24wg1AQul+D1GantF8wlKkzsd1rAMtMwWKw/2gEhI/z2nXALVdRMlOOc+ULnhZHJafqkjbseoGOZ4171GaA6PSBOd53n0g5CpAwA0UkaWHIKC8442X7rpHjcQiXzbMNA7svL3rya0H9WZd4xDMV8GqlBYDUFO8uEcTGl0dADnXSsj63QoU33brDRC1C9xo3xtZVeSu4KnA+r0vZa47fMjUol4eibOYptZVV1R9VgBQj5BFI8OoLd20Q5QQKXzwr5NHUvA4NoGpbzt+4VbjTILOZPszZvP9pfdxqLc49ic9zAhWJv3zajJVdQGv8Z+yPzdOaKd+LHOeikKmSAa4zoMQFFz+MCp0p44ZS54HMk9HfTukm/uo2H1mbE9E59WrHen3Ma5Nt1g3b1MAzPUmr1ZcG0RBIwg9+aoDF5k= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
